apiVersion: apps/v1
kind: Deployment
metadata:
 name: server-dep
 labels:
  app: server
spec:
 replicas: 1
 selector:
  matchLabels:
   app: server
 template:
  metadata:
   labels:
    app: server
  spec:
   containers:
    - name: server
      image: kvarc/final-test-server:latest
      ports:
       - name: api-service
         containerPort: 1514
---
apiVersion: v1
kind: Service
metadata:
  name: hello-k3s
spec:
  type: LoadBalancer
  ports:
  - protocol: UDP
    port: 1514
    targetPort: 1514
  selector:
    app: server
